### ISSUE TITLE
Add option for access path in s3 oauth

### ISSUE THREAD

**Issue by matt-fagan** [socialcopsdev/flyio#18]
In some use cases, authorization is only granted at a specific sub-path level, as opposed to a master path. Enabling users to set a landing path could allow access in these use cases.

**Comment by himanshu-sikaria** [comment]
Users with access to a specific path can still access the files (read or write depending on the permissions they have) using the current functions.

For example, in a bucket `flyio-test` if I have access to a folder  `test1` and don't have access to `test2` then 

`list_files()` will throw an Access Denied error
`list_files("test1")` will show the files in that folder
`list_files("test2")` will again throw an error

Generally, it could be helpful to have something similar to setwd() and getwd() for the cloud functions

**Comment by matt-fagan** [comment]
Thank you himanshu, I am usually like a lost puppy if a help doc doesn't have the exact use case I experience. Works wonderfully!
