### ISSUE TITLE
Mismatch in import and export arguments for shapefiles 

### ISSUE THREAD

**Issue by shilpa9a** [socialcopsdev/flyio#19]
- [x] In case of export_shp, function demands dsn/path and layer to be passed as one argument and in case of import_shp, it demands dsn/path and layer as separate arguments.
- [ ] As import_shp requires separate path and layer argument, it doesn't work for shapefile function of raster package

**Comment by himanshu-sikaria** [comment]
shapefile from the raster library requires the files to be locally present and currently once the object is loaded in R the local copy is deleted. Will need to look into this to solve for `raster` library generally

**Comment by himanshu-sikaria** [comment]
Closing this, will be solved in #21
